### ISSUE TITLE
Unable to scrape data: hass variable not set on template

### ISSUE THREAD

**Issue by johntdyer** [danieldotnl/ha-multiscrape#391] opened 2024-08-02 23:27 UTC
Since 2025.08.00b I have been getting an error on most of my multiscrape sensors, all of which worked fine before.

## Version of the custom_component
7.0.2

## Configuration

```yaml
---
- name: Hue Sync Box Rest
  resource: https://192.168.120.152/api/v1/execution
  verify_ssl: false
  log_response: true
  timeout: 60
  headers:
    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
    Authorization: !secret hue_sync_box_token_bearer
  sensor:
    - unique_id: Hue Sync Box
      name: Hue Sync Box
      value_template: "foo"
      icon: mdi:devices
      attributes:
        - name: syncActive
          value_template: >
            {{ value.syncActive }}
        - name: video
          value_template: >
            {{ value.video }}
        - name: game
          value_template: >
            {{ value.game }}
        - name: music
          value_template: >
            {{ value.music }}
        - name: hdmiSource
          value_template: >
            {{ value.hdmiSource }}

      # state_class: measurement

```

## Describe the bug

```
2024-08-02 19:22:02.537 ERROR (MainThread) [custom_components.multiscrape.sensor] Hue Sync Box Rest # Hue Sync Box # Unable to scrape data: hass variable not set on template

```

## Debug log

```text

2024-08-02 19:22:01.466 DEBUG (MainThread) [custom_components.multiscrape] # Start processing config from configuration.yaml

2024-08-02 19:22:01.467 DEBUG (MainThread) [custom_components.multiscrape] Hue Sync Box Rest # Setting up multiscrape with config:
 {'name': 'Hue Sync Box Rest', 'resource': 'https://192.168.120.152/api/v1/execution', 'verify_ssl': False, 'log_response': True, 'timeout': 60, 'headers': {'User-Agent': Template<template=(Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36) renders=0>, 'Authorization': Template<template=(Bearer xxxxxxxx=xxxxx=) renders=0>}, 'sensor': [{'unique_id': 'Hue Sync Box', 'name': 'Hue Sync Box', 'value_template': Template<template=({{ value.syncActive }}) renders=0>, 'icon': Template<template=(mdi:devices) renders=0>, 'force_update': False}], 'method': 'GET', 'list_separator': ',', 'parser': 'lxml'}
2024-08-02 19:22:01.467 DEBUG (MainThread) [custom_components.multiscrape] Hue Sync Box Rest # Log responses enabled, creating logging folder: /config/multiscrape/hue_sync_box_rest/
2024-08-02 19:22:01.666 DEBUG (MainThread) [custom_components.multiscrape.http] Hue Sync Box Rest # Initializing http wrapper
2024-08-02 19:22:01.666 DEBUG (MainThread) [custom_components.multiscrape.scraper] Hue Sync Box Rest # Creating scraper
2024-08-02 19:22:01.666 DEBUG (MainThread) [custom_components.multiscrape.scraper] Hue Sync Box Rest # Initializing scraper
2024-08-02 19:22:01.666 DEBUG (MainThread) [custom_components.multiscrape.coordinator] Hue Sync Box Rest # Creating ContentRequestManager
2024-08-02 19:22:01.666 DEBUG (MainThread) [custom_components.multiscrape.coordinator] Hue Sync Box Rest # Creating coordinator
2024-08-02 19:22:01.666 DEBUG (MainThread) [custom_components.multiscrape.coordinator] Hue Sync Box Rest # Scan interval is 0:01:00
2024-08-02 19:22:01.666 DEBUG (MainThread) [custom_components.multiscrape.service] Hue Sync Box Rest # Setting up multiscrape configuration level services




2024-08-02 19:22:01.761 DEBUG (MainThread) [custom_components.multiscrape.coordinator] Hue Sync Box Rest # New run: start (re)loading data from resource
2024-08-02 19:22:01.761 DEBUG (MainThread) [custom_components.multiscrape.coordinator] Hue Sync Box Rest # Deleting logging files from previous run
2024-08-02 19:22:01.776 DEBUG (MainThread) [custom_components.multiscrape.http] Hue Sync Box Rest # Executing page-request with a GET to url: https://192.168.120.152/api/v1/execution with headers: {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36', 'Authorization': 'Bearer xxxxxxxx=xxxxx='}.
2024-08-02 19:22:01.781 DEBUG (MainThread) [custom_components.multiscrape.http] Hue Sync Box Rest # request_headers written to file: page_request_headers.txt
2024-08-02 19:22:01.787 DEBUG (MainThread) [custom_components.multiscrape.coordinator] Finished fetching multiscrape data in 0.026 seconds (success: True)
2024-08-02 19:22:01.787 DEBUG (MainThread) [custom_components.multiscrape.coordinator] Finished fetching multiscrape data in 0.028 seconds (success: True)
2024-08-02 19:22:01.791 DEBUG (MainThread) [custom_components.multiscrape.http] Hue Sync Box Rest # request_body written to file: page_request_body.txt
2024-08-02 19:22:01.805 DEBUG (MainThread) [custom_components.multiscrape.coordinator] Finished fetching multiscrape data in 0.043 seconds (success: True)
2024-08-02 19:22:01.863 DEBUG (MainThread) [custom_components.multiscrape.coordinator] Finished fetching multiscrape data in 0.101 seconds (success: True)
2024-08-02 19:22:02.429 DEBUG (MainThread) [custom_components.multiscrape.http] Hue Sync Box Rest # Response status code received: 200
2024-08-02 19:22:02.430 DEBUG (MainThread) [custom_components.multiscrape.http] Hue Sync Box Rest # response_headers written to file: page_response_headers.txt
2024-08-02 19:22:02.431 DEBUG (MainThread) [custom_components.multiscrape.http] Hue Sync Box Rest # response_body written to file: page_response_body.txt
2024-08-02 19:22:02.431 DEBUG (MainThread) [custom_components.multiscrape.scraper] Hue Sync Box Rest # Response seems to be json. Skip parsing with BeautifulSoup.
2024-08-02 19:22:02.431 DEBUG (MainThread) [custom_components.multiscrape.coordinator] Hue Sync Box Rest # Data successfully refreshed. Sensors will now start scraping to update.
2024-08-02 19:22:02.431 DEBUG (MainThread) [custom_components.multiscrape.coordinator] Finished fetching multiscrape data in 0.671 seconds (success: True)
2024-08-02 19:22:02.532 DEBUG (MainThread) [custom_components.multiscrape.coordinator] Finished fetching multiscrape data in 0.771 seconds (success: True)
2024-08-02 19:22:02.533 INFO (MainThread) [homeassistant.components.sensor] Setting up multiscrape.sensor
2024-08-02 19:22:02.536 INFO (MainThread) [homeassistant.components.sensor] Setting up multiscrape.sensor
2024-08-02 19:22:02.537 DEBUG (MainThread) [custom_components.multiscrape.sensor] Hue Sync Box Rest # Hue Sync Box # Setting up sensor
2024-08-02 19:22:02.537 DEBUG (MainThread) [custom_components.multiscrape.sensor] Hue Sync Box Rest # Hue Sync Box # Start scraping to update sensor
2024-08-02 19:22:02.537 DEBUG (MainThread) [custom_components.multiscrape.scraper] Hue Sync Box Rest # Hue Sync Box # Applying value_template only.
2024-08-02 19:22:02.537 ERROR (MainThread) [custom_components.multiscrape.sensor] Hue Sync Box Rest # Hue Sync Box # Unable to scrape data: hass variable not set on template
Consider using debug logging and log_response for further investigation.
2024-08-02 19:22:02.537 DEBUG (MainThread) [custom_components.multiscrape.sensor] Hue Sync Box Rest # Hue Sync Box # On-error, set value to None
2024-08-02 19:22:02.537 DEBUG (MainThread) [custom_components.multiscrape.entity] Hue Sync Box Rest # Hue Sync Box # Icon template rendered and set to: mdi:devices
2024-08-02 19:22:02.537 DEBUG (MainThread) [custom_components.multiscrape.entity] Hue Sync Box Rest # Hue Sync Box # Updated sensor and attributes, now adding to HA
2024-08-02 19:22:02.546 INFO (MainThread) [homeassistant.components.sensor] Setting up multiscrape.sensor
2024-08-02 19:22:02.549 INFO (MainThread) [homeassistant.components.sensor] Setting up multiscrape.sensor
Consider using debug logging and log_response for further investigation.
2024-08-02 19:22:02.558 INFO (MainThread) [homeassistant.components.sensor] Setting up multiscrape.sensor
Consider using debug logging and log_response for further investigation.
2024-08-02 19:22:02.563 INFO (MainThread) [homeassistant.components.sensor] Setting up multiscrape.sensor
Consider using debug logging and log_response for further investigation.
2024-08-02 19:22:02.567 INFO (MainThread) [homeassistant.components.sensor] Setting up multiscrape.sensor
2024-08-02 19:22:02.568 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up multiscrape platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/multiscrape/sensor.py", line 68, in async_setup_platform
    sensor_selector = Selector(hass, conf)
                      ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/multiscrape/selector.py", line 33, in __init__
    raise ValueError(
ValueError: Selector error: either select, select_list or a value_template should be provided.


```

**Comment by johntdyer** [comment] 2024-08-03 15:04
So, FWIW I tried the example straight from your readme and got the same error

```
- name: HA scraper
    resource: https://www.home-assistant.io
    scan_interval: 3600
    sensor:
      - unique_id: ha_latest_version
        name: Latest version
        select: ".release-date"
        value_template: "{{ value | trim }}"
      - unique_id: ha_release_date
        icon: >-
          {% if is_state('binary_sensor.ha_version_check', 'on') %}
            mdi:alarm-light
          {% else %}
            mdi:bat
          {% endif %}
        name: Release date
        select: ".release-date"
        attribute: "title"
        value_template: "{{ (value.split('released')[1]) }}"
    binary_sensor:
      - unique_id: ha_version_check
        name: Latest version == 2021.7.0
        select: ".release-date"
        value_template: '{{ value | trim == "2021.7.0" }}'
        attributes:
          - name: Release notes link
            select: ".release-date"
            attribute: href
```


```
2024-08-03 11:03:49.720 DEBUG (MainThread) [custom_components.multiscrape] # Start processing config from configuration.yaml
2024-08-03 11:03:49.721 DEBUG (MainThread) [custom_components.multiscrape] HA scraper # Setting up multiscrape with config:
 {'name': 'HA scraper', 'resource': 'https://www.home-assistant.io', 'scan_interval': datetime.timedelta(seconds=3600), 'sensor': [{'unique_id': 'ha_latest_version', 'name': 'Latest version', 'select': Template<template=(.release-date) renders=0>, 'value_template': Template<template=({{ value | trim }}) renders=0>, 'force_update': False}, {'unique_id': 'ha_release_date', 'icon': Template<template=({% if is_state('binary_sensor.ha_version_check', 'on') %}
  mdi:alarm-light
{% else %}
  mdi:bat
{% endif %}) renders=0>, 'name': 'Release date', 'select': Template<template=(.release-date) renders=0>, 'attribute': 'title', 'value_template': Template<template=({{ (value.split('released')[1]) }}) renders=0>, 'force_update': False}], 'binary_sensor': [{'unique_id': 'ha_version_check', 'name': 'Latest version == 2021.7.0', 'select': Template<template=(.release-date) renders=0>, 'value_template': Template<template=({{ value | trim == "2021.7.0" }}) renders=0>, 'attributes': [{'name': 'Release notes link', 'select': Template<template=(.release-date) renders=0>, 'attribute': 'href'}], 'force_update': False}], 'method': 'GET', 'timeout': 10, 'verify_ssl': True, 'list_separator': ',', 'parser': 'lxml', 'log_response': False}
2024-08-03 11:03:49.721 DEBUG (MainThread) [custom_components.multiscrape.http] HA scraper # Initializing http wrapper
2024-08-03 11:03:49.721 DEBUG (MainThread) [custom_components.multiscrape.scraper] HA scraper # Creating scraper
2024-08-03 11:03:49.721 DEBUG (MainThread) [custom_components.multiscrape.scraper] HA scraper # Initializing scraper
2024-08-03 11:03:49.721 DEBUG (MainThread) [custom_components.multiscrape.coordinator] HA scraper # Creating ContentRequestManager
2024-08-03 11:03:49.721 DEBUG (MainThread) [custom_components.multiscrape.coordinator] HA scraper # Creating coordinator
2024-08-03 11:03:49.721 DEBUG (MainThread) [custom_components.multiscrape.coordinator] HA scraper # Scan interval is 1:00:00
2024-08-03 11:03:49.721 DEBUG (MainThread) [custom_components.multiscrape.service] HA scraper # Setting up multiscrape configuration level services
2024-08-03 11:03:49.721 DEBUG (MainThread) [custom_components.multiscrape] Hass Main config multiscape # Setting up multiscrape with config:
 {'name': 'Hass Main config multiscape', 'resource': 'http://192.168.120.3:8123/api/config', 'verify_ssl': False, 'log_response': True, 'timeout': 60, 'headers': {'User-Agent': Template<template=(Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36) renders=0>, 'Authorization': Template<template=(Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJiODRjNDRmZWUxN2Y0NmY3OTY1NWE3NzdlOGNlMjA3YSIsImlhdCI6MTYwODY2ODY2OCwiZXhwIjoxOTI0MDI4NjY4fQ.wr_uPBSYSOO7KCb_32o3uwlf34dYkFnBE7NzEoQ8h3g) renders=0>}, 'sensor': [{'unique_id': 'hass_main_config', 'name': 'Hass Main config', 'icon': Template<template=(mdi:devices) renders=0>, 'attributes': [{'name': 'components', 'value_template': Template<template=({{ value_json.components | default }}) renders=0>}, {'name': 'unit_system', 'value_template': Template<template=({{ value_json.unit_system | default }}) renders=0>}, {'name': 'config_dir', 'value_template': Template<template=({{ value_json.config_dir | default }}) renders=0>}, {'name': 'version', 'value_template': Template<template=({{ value_json.version | default }}) renders=0>}], 'force_update': False}], 'method': 'GET', 'list_separator': ',', 'parser': 'lxml'}
2024-08-03 11:03:49.722 DEBUG (MainThread) [custom_components.multiscrape] Hass Main config multiscape # Log responses enabled, creating logging folder: /config/multiscrape/hass_main_config_multiscape/
2024-08-03 11:03:49.728 DEBUG (MainThread) [custom_components.multiscrape.http] Hass Main config multiscape # Initializing http wrapper
2024-08-03 11:03:49.728 DEBUG (MainThread) [custom_components.multiscrape.scraper] Hass Main config multiscape # Creating scraper
2024-08-03 11:03:49.728 DEBUG (MainThread) [custom_components.multiscrape.scraper] Hass Main config multiscape # Initializing scraper
2024-08-03 11:03:49.728 DEBUG (MainThread) [custom_components.multiscrape.coordinator] Hass Main config multiscape # Creating ContentRequestManager
2024-08-03 11:03:49.728 DEBUG (MainThread) [custom_components.multiscrape.coordinator] Hass Main config multiscape # Creating coordinator
2024-08-03 11:03:49.728 DEBUG (MainThread) [custom_components.multiscrape.coordinator] Hass Main config multiscape # Scan interval is 0:01:00
2024-08-03 11:03:49.728 DEBUG (MainThread) [custom_components.multiscrape.service] Hass Main config multiscape # Setting up multiscrape configuration level services
2024-08-03 11:03:49.730 DEBUG (MainThread) [custom_components.multiscrape.coordinator] HA scraper # New run: start (re)loading data from resource
2024-08-03 11:03:49.730 DEBUG (MainThread) [custom_components.multiscrape.http] HA scraper # Executing page-request with a GET to url: https://www.home-assistant.io with headers: {}.
2024-08-03 11:03:49.731 DEBUG (MainThread) [custom_components.multiscrape.coordinator] Hass Main config multiscape # New run: start (re)loading data from resource
2024-08-03 11:03:49.731 DEBUG (MainThread) [custom_components.multiscrape.coordinator] Hass Main config multiscape # Deleting logging files from previous run
2024-08-03 11:03:50.211 DEBUG (MainThread) [custom_components.multiscrape.http] Hass Main config multiscape # Executing page-request with a GET to url: http://192.168.120.3:8123/api/config with headers: {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJiODRjNDRmZWUxN2Y0NmY3OTY1NWE3NzdlOGNlMjA3YSIsImlhdCI6MTYwODY2ODY2OCwiZXhwIjoxOTI0MDI4NjY4fQ.wr_uPBSYSOO7KCb_32o3uwlf34dYkFnBE7NzEoQ8h3g'}.
2024-08-03 11:03:50.230 DEBUG (MainThread) [custom_components.multiscrape.http] Hass Main config multiscape # request_headers written to file: page_request_headers.txt
2024-08-03 11:03:50.232 DEBUG (MainThread) [custom_components.multiscrape.http] Hass Main config multiscape # request_body written to file: page_request_body.txt
2024-08-03 11:03:50.237 DEBUG (MainThread) [custom_components.multiscrape.http] Hass Main config multiscape # Response status code received: 200
2024-08-03 11:03:50.239 DEBUG (MainThread) [custom_components.multiscrape.http] Hass Main config multiscape # response_headers written to file: page_response_headers.txt
2024-08-03 11:03:50.240 DEBUG (MainThread) [custom_components.multiscrape.http] Hass Main config multiscape # response_body written to file: page_response_body.txt
2024-08-03 11:03:50.240 DEBUG (MainThread) [custom_components.multiscrape.scraper] Hass Main config multiscape # Response seems to be json. Skip parsing with BeautifulSoup.
2024-08-03 11:03:50.240 DEBUG (MainThread) [custom_components.multiscrape.coordinator] Hass Main config multiscape # Data successfully refreshed. Sensors will now start scraping to update.
2024-08-03 11:03:50.240 DEBUG (MainThread) [custom_components.multiscrape.coordinator] Finished fetching multiscrape data in 0.509 seconds (success: True)
2024-08-03 11:03:50.267 DEBUG (MainThread) [custom_components.multiscrape.http] HA scraper # Response status code received: 200
2024-08-03 11:03:50.267 DEBUG (MainThread) [custom_components.multiscrape.scraper] HA scraper # Loading the content in BeautifulSoup.
2024-08-03 11:03:50.282 DEBUG (MainThread) [custom_components.multiscrape.coordinator] HA scraper # Data successfully refreshed. Sensors will now start scraping to update.
2024-08-03 11:03:50.282 DEBUG (MainThread) [custom_components.multiscrape.coordinator] Finished fetching multiscrape data in 0.552 seconds (success: True)
2024-08-03 11:03:50.283 INFO (MainThread) [homeassistant.components.sensor] Setting up multiscrape.sensor
2024-08-03 11:03:50.283 DEBUG (MainThread) [custom_components.multiscrape.sensor] HA scraper # Latest version # Setting up sensor
2024-08-03 11:03:50.283 DEBUG (MainThread) [custom_components.multiscrape.sensor] HA scraper # Latest version # Start scraping to update sensor
2024-08-03 11:03:50.284 DEBUG (MainThread) [custom_components.multiscrape.scraper] HA scraper # Latest version # Tag selected: <a class="release-date" href="/blog/2024/07/03/release-20247/" title="Latest version 2024.7.4 released July 30, 2024">
2024.7.4
</a>
2024-08-03 11:03:50.284 DEBUG (MainThread) [custom_components.multiscrape.scraper] HA scraper # Latest version # Selector result:
2024.7.4

2024-08-03 11:03:50.284 DEBUG (MainThread) [custom_components.multiscrape.scraper] HA scraper # Latest version # Applying value_template on selector result
2024-08-03 11:03:50.284 ERROR (MainThread) [custom_components.multiscrape.sensor] HA scraper # Latest version # Unable to scrape data: hass variable not set on template
Consider using debug logging and log_response for further investigation.
2024-08-03 11:03:50.284 DEBUG (MainThread) [custom_components.multiscrape.sensor] HA scraper # Latest version # On-error, set value to None
2024-08-03 11:03:50.284 DEBUG (MainThread) [custom_components.multiscrape.entity] HA scraper # Latest version # Updated sensor and attributes, now adding to HA
2024-08-03 11:03:50.285 INFO (MainThread) [homeassistant.components.sensor] Setting up multiscrape.sensor
2024-08-03 11:03:50.285 DEBUG (MainThread) [custom_components.multiscrape.sensor] HA scraper # Release date # Setting up sensor
2024-08-03 11:03:50.286 DEBUG (MainThread) [custom_components.multiscrape.sensor] HA scraper # Release date # Start scraping to update sensor
2024-08-03 11:03:50.286 DEBUG (MainThread) [custom_components.multiscrape.scraper] HA scraper # Release date # Tag selected: <a class="release-date" href="/blog/2024/07/03/release-20247/" title="Latest version 2024.7.4 released July 30, 2024">
2024.7.4
</a>
2024-08-03 11:03:50.286 DEBUG (MainThread) [custom_components.multiscrape.scraper] HA scraper # Release date # Try to find attribute: title
2024-08-03 11:03:50.286 DEBUG (MainThread) [custom_components.multiscrape.scraper] HA scraper # Release date # Selector result: Latest version 2024.7.4 released July 30, 2024
2024-08-03 11:03:50.286 DEBUG (MainThread) [custom_components.multiscrape.scraper] HA scraper # Release date # Applying value_template on selector result
2024-08-03 11:03:50.286 ERROR (MainThread) [custom_components.multiscrape.sensor] HA scraper # Release date # Unable to scrape data: hass variable not set on template
Consider using debug logging and log_response for further investigation.
2024-08-03 11:03:50.287 DEBUG (MainThread) [custom_components.multiscrape.sensor] HA scraper # Release date # On-error, set value to None
2024-08-03 11:03:50.287 DEBUG (MainThread) [custom_components.multiscrape.entity] HA scraper # Release date # Icon template rendered and set to: mdi:bat
2024-08-03 11:03:50.287 DEBUG (MainThread) [custom_components.multiscrape.entity] HA scraper # Release date # Updated sensor and attributes, now adding to HA
2024-08-03 11:03:50.287 DEBUG (MainThread) [custom_components.multiscrape.binary_sensor] HA scraper # Latest version == 2021.7.0 # Setting up binary sensor
2024-08-03 11:03:50.288 DEBUG (MainThread) [custom_components.multiscrape.binary_sensor] HA scraper # Latest version == 2021.7.0 # Start scraping to update sensor
2024-08-03 11:03:50.289 DEBUG (MainThread) [custom_components.multiscrape.scraper] HA scraper # Latest version == 2021.7.0 # Tag selected: <a class="release-date" href="/blog/2024/07/03/release-20247/" title="Latest version 2024.7.4 released July 30, 2024">
2024.7.4
</a>
2024-08-03 11:03:50.289 DEBUG (MainThread) [custom_components.multiscrape.scraper] HA scraper # Latest version == 2021.7.0 # Selector result:
2024.7.4

2024-08-03 11:03:50.289 DEBUG (MainThread) [custom_components.multiscrape.scraper] HA scraper # Latest version == 2021.7.0 # Applying value_template on selector result
2024-08-03 11:03:50.289 ERROR (MainThread) [custom_components.multiscrape.binary_sensor] HA scraper # Latest version == 2021.7.0 # Unable to scrape data: hass variable not set on template.
Consider using debug logging and log_response for further investigation.
2024-08-03 11:03:50.289 DEBUG (MainThread) [custom_components.multiscrape.binary_sensor] HA scraper # Latest version == 2021.7.0 # On-error, set value to None
2024-08-03 11:03:50.289 DEBUG (MainThread) [custom_components.multiscrape.entity] HA scraper # Latest version == 2021.7.0 # Start scraping attributes
2024-08-03 11:03:50.289 DEBUG (MainThread) [custom_components.multiscrape.scraper] HA scraper # Latest version == 2021.7.0# release_notes_link # Tag selected: <a class="release-date" href="/blog/2024/07/03/release-20247/" title="Latest version 2024.7.4 released July 30, 2024">
2024.7.4
</a>
2024-08-03 11:03:50.289 DEBUG (MainThread) [custom_components.multiscrape.scraper] HA scraper # Latest version == 2021.7.0# release_notes_link # Try to find attribute: href
2024-08-03 11:03:50.289 DEBUG (MainThread) [custom_components.multiscrape.scraper] HA scraper # Latest version == 2021.7.0# release_notes_link # Selector result: /blog/2024/07/03/release-20247/
2024-08-03 11:03:50.289 DEBUG (MainThread) [custom_components.multiscrape.scraper] HA scraper # Latest version == 2021.7.0# release_notes_link # Final selector value: /blog/2024/07/03/release-20247/ of type <class 'str'>
2024-08-03 11:03:50.289 DEBUG (MainThread) [custom_components.multiscrape.entity] HA scraper # Latest version == 2021.7.0 # Updated sensor and attributes, now adding to HA
2024-08-03 11:03:50.292 INFO (MainThread) [homeassistant.components.sensor] Setting up multiscrape.sensor
2024-08-03 11:03:50.292 DEBUG (MainThread) [custom_components.multiscrape.sensor] Hass Main config multiscape # Hass Main config # Setting up sensor
2024-08-03 11:03:50.292 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up multiscrape platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/multiscrape/sensor.py", line 68, in async_setup_platform
    sensor_selector = Selector(hass, conf)
                      ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/multiscrape/selector.py", line 33, in __init__
    raise ValueError(
ValueError: Selector error: either select, select_list or a value_template should be provided.
2024-08-03 11:03:53.367 WARNING (MainThread) [pyweatherflow_forecast.wffcst_lib] Weather Station either is offline or no recent observations.
2024-08-03 11:03:53.416 WARNING (MainThread) [custom_components.weatherflow_forecast] Weather Station either is offline or no recent observations from station. Remove Sensors to avoid this warning.


```

**Comment by danieldotnl** [comment] 2024-08-03 15:57
Thanks for reporting! I will have a look as soon as possible or maybe @jeremicmilan is able to take a look as it involves his PR?

Note that it is a pre-release, so please downgrade to the latest official release for the quickest solution.

**Comment by jeremicmilan** [comment] 2024-08-03 16:30
I'll take a look tonight. I don't have hue, but hopefully the logs will be enough to figure out what's going on.

**Comment by johntdyer** [comment] 2024-08-03 17:10
Here is the response incase its needed

```json
{"mode":"video","syncActive":true,"hdmiActive":true,"hdmiSource":"input1","hueTarget":"xxxx-xxx-xxxx-xxxx-xxxx9ac","brightness":200,"lastSyncMode":"video","video":{"intensity":"intense","backgroundLighting":true},"game":{"intensity":"intense","backgroundLighting":false},"music":{"intensity":"intense","palette":"melancholicEnergetic"},"preset":null}
```

**Comment by johntdyer** [comment] 2024-08-03 17:40
So one thing I found troubleshooting other errors is that the Alexa Media player app is throwing a similiar error re: the hass variable...

```
2024-08-03 13:38:48.505 ERROR (MainThread) [custom_components.monitor_docker] Failed Docker connect: tcp://192.168.100.3:2375/version
2024-08-03 13:38:48.506 ERROR (MainThread) [custom_components.monitor_docker] Retry in 60 seconds
2024-08-03 13:38:51.286 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session (None)
2024-08-03 13:38:51.387 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxxxxxx@gmail.com - amazon.com for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 360, in async_setup_entry
    if await test_login_status(hass, config_entry, login):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 1396, in test_login_status
    async_create_persistent_notification(
TypeError: async_create() missing 1 required positional argument: 'hass'
```

**Comment by jeremicmilan** [comment] 2024-08-03 21:17
I'm not reproducing this issue on the latest stable version of HA: 2024.7.4. I'm not updating my production server to check this. @danieldotnl, do you know how to change HA version in the dev environment (since 2024.7.4 is being initialized there as well)?
Also, since it is happening with other integrations, I would say that this is an issue with hass core. Examining the shared traces and the code hints at hass core as well.
Can you please downgrade to the stable version of multi-scrape and see if the issue happens again?

**Comment by hmmbob** [comment] 2024-08-04 14:07
Seeing this on my 2024.0.8b1 as well, on 2024.7 it all works fine.

I have 2 multiscrape URLs setup: one is based on only html selectors (and works completely fine), the other is based on JSON parsing (with a template) and is broken. Not sure where we need to throw in the `hass` argument though.

**Comment by jeremicmilan** [comment] 2024-08-04 18:40
You do not need to specify anything. This seems like a regression in Hass core. The bug needs to filled there. I'm AFK at the moment and cannot check if a bug already exists for this in hass core.

**Comment by danieldotnl** [comment] 2024-08-04 19:28
@jeremicmilan: Apologies for involving you. I read `variables` and I thought it must be your PR since I just merged that. However, this is already happening in v7.0.2.

**Comment by danieldotnl** [comment] 2024-08-04 19:29
What I know so far:
The error is correct, the hass variable isn't set. This is caused by a change in HA core as of release 2024.08.0b0. Somehow the hass variable is having a different value than before, already in the `async_setup_platform` function.
So this is either a bug in HA core, or something changed there which requires a change in custom components using the hass variable in some way or at some place.

I'll keep investigating.

**Comment by danieldotnl** [comment] 2024-08-04 19:53
> @danieldotnl, do you know how to change HA version in the dev environment (since 2024.7.4 is being initialized there as well)? 

Normally I'm relying on `pytest-homeassistant-custom-component` for the HA version. They usually create a new version automatically after each HA release, and this results in a PR on Multiscrape side. However, for some reason they didn't for the 204.08 pre-releases.

For now I removed `pytest-homeassistant-custom-component` from requirements.txt and added `homeassistant==2024.08.0b0`. Then run `./scripts/setup`.

**Comment by hmmbob** [comment] 2024-08-04 19:59
I have raised this in the [#beta discord](https://discord.com/channels/330944238910963714/427516175237382144/1269646452263620709), but Did not get many replies there

**Comment by danieldotnl** [comment] 2024-08-04 20:22
Yeah, I read that earlier tonight.

**Comment by johntdyer** [comment] 2024-08-04 21:48
Bumped conversation again just to make sure its not lost in the daily shuffle of that channel 

https://discord.com/channels/330944238910963714/427516175237382144/1269765596006842429

**Comment by danieldotnl** [comment] 2024-08-05 09:23
So I currently think it's an issue in core:
https://discord.com/channels/330944238910963714/427516175237382144/1269948432672620545

**Comment by danieldotnl** [comment] 2024-08-05 16:36
I have no idea what causes the issue (since 2024.8), but I have a quick and dirty fix prepared, which I'll release before Wednesday in case there's is no more clarity.

**Comment by danieldotnl** [comment] 2024-08-06 20:06
Released: https://github.com/danieldotnl/ha-multiscrape/releases/tag/v7.0.3

**Closed** 2024-08-06 20:40 UTC

**Comment by hmmbob** [comment] 2024-08-07 15:41
Fixed. Tx!

**Comment by hmmbob** [comment] 2024-08-10 17:25
For others; it's a regression in HA 2024.8: https://github.com/home-assistant/core/issues/123251#issuecomment-2275833529

2024.8.1 should have the fix, when it gets released (prob later today, Frenck started the release about 40mins ago)
