### ISSUE TITLE
Dependency Update in HA Core: Lxml

### ISSUE THREAD

**Issue by mjtappert** [danieldotnl/ha-multiscrape#301] opened 2023-12-31 21:13 UTC
As of HA 2024.1.0b3 the core lxml dependency / minimum version has been updated to 4.9.4 

See: https://github.com/home-assistant/core/pull/106694/files

Once the Alpine 3.18 build issue has been resolved, it appears core will likely update to lxml 5.0.x or 5.0.0.x in the near future, as well.

I know this doesn't include configs or logs, but hopefully this makes sense as it is a core dep update.

**Comment by codyc1515** [comment] 2024-01-01 19:35
Here is the log:

```
Logger: homeassistant.setup
Source: setup.py:221
First occurred: January 1, 2024 at 17:24:45 (1 occurrences)
Last logged: January 1, 2024 at 17:24:45

Setup failed for custom integration 'multiscrape': Requirements for multiscrape not found: ['lxml==4.9.1'].
```

**Comment by danieldotnl** [comment] 2024-01-01 21:51
Thank you for reporting this!
Fixed in: [Release v6.7.5](https://github.com/danieldotnl/ha-multiscrape/releases/tag/v6.7.5)

**Comment by pbranly** [comment] 2024-01-02 05:29
Hi this is not working on my side with the 6.7.1 version 

Setup failed for custom integration 'multiscrape': Requirements for multiscrape not found: ['lxml==5.0.0'].

Please reopen 
Phil

**Comment by codyc1515** [comment] 2024-01-02 05:57
? The latest version is not 5. Why would you change it to that?

**Comment by danieldotnl** [comment] 2024-01-02 07:57
Not sure what's going wrong. I admit I was in a hurry, but it works for me on 2023.12.4.
And 5.0.0 is the latest lxml version, released on December 29th:

https://pypi.org/project/lxml/

I removed the release for now and will try to look into it tonight.

**Comment by mhoogenbosch** [comment] 2024-01-02 07:58
The integration doesn’t start. Maybe the version is correct. 

I got the same error with the just installed version:

logger:%20homeassistant.setup%0ASource%3A%20setup.py%3A221%0AFirst%20occurred%3A%2008%3A46%3A15%20(1%20occurrences)%0ALast%20logged%3A%2008%3A46%3A15%0A%0ASetup%20failed%20for%20custom%20integration%20'multiscrape'%3A%20Requirements%20for%20multiscrape%20not%20found%3A%20%5B'lxml==5.0.0'%5D.

**Comment by mhoogenbosch** [comment] 2024-01-02 08:00
> Not sure what's going wrong. I admit I was in a hurry, but it works for me on 2023.12.4. And 5.0.0 is the latest lxml version, released on December 29th:
> 
> https://pypi.org/project/lxml/
> 
> I removed the release for now and will try to look into it tonight.

This is on beta of 2024.1.0 , maybe that’s the difference. 2023.12.4 worked fine for me too.

**Comment by hmmbob** [comment] 2024-01-02 09:06
@danieldotnl This is said on the topic in the [HA beta discord](https://discord.com/channels/330944238910963714/427516175237382144/1191608959396741221):

![image](https://github.com/danieldotnl/ha-multiscrape/assets/33529490/970e7c70-6be9-46b9-a28e-05bcaad8af97)

and this [earlier](https://discord.com/channels/330944238910963714/427516175237382144/1191112614365888522):

![image](https://github.com/danieldotnl/ha-multiscrape/assets/33529490/7f97fd65-9c7e-49fb-ac18-eb0203bb8526)

**Comment by pbranly** [comment] 2024-01-02 09:06
Him yes the issue is with HA new 01 beta releases 
This is surely the reason
Phil

**Comment by pbranly** [comment] 2024-01-02 09:12
I revert back to 6.7.4 and th error is now:

Setup failed for custom integration 'multiscrape': Requirements for multiscrape not found: ['lxml==4.9.1'].
Phil

**Comment by danieldotnl** [comment] 2024-01-02 15:44
Released again in v6.7.6!

**Comment by mhoogenbosch** [comment] 2024-01-02 16:14
I can confirm it is working again.

**Comment by danieldotnl** [comment] 2024-01-02 19:44
Thanks for confirming and thanks to everybody involved for helping to solve this issue and make sure the many Multiscrape users (1036 users today who share their HA usage data) will have a smooth upgrade to the 2024.1 release tomorrow!

**Closed by danieldotnl** 2024-01-02 19:44 UTC

**Comment by hmmbob** [comment] 2024-01-02 20:07
Of course. @danieldotnl did you ever consider to contribute this to core, to replace the current scrape integration?

**Comment by danieldotnl** [comment] 2024-01-02 20:49
Well, I've thought about it a little. But I don't think it will be easily accepted, especially with the quite specific form-submit feature.
Besides that, I like the flexibility of releasing whatever and whenever I want.

**Comment by tOOmki** [comment] 2024-01-30 21:11
Core 2024.1.5
Supervisor 2023.12.1
Operating System 11.4

“Setup failed for custom integration ‘multiscrape’: Requirements for multiscrape not found: [‘lxml==4.9.1’].”

I use:
master - v6.8.1
renovate/homeassistant-2024.x 

I try manual install:
pip install lxml==4.9.1
Restart HA
pip show lxml
“WARNING Package(s) not found lxml.”

“Unable to install package lxml==4.9.1: ERROR: Cannot install lxml==4.9.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit [Dependency Resolution - pip documentation v24.0.dev0](https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts)”
