### ISSUE TITLE
Error adding entities for domain sensor with platform multiscrape

### ISSUE THREAD

**Issue by ErichRa** [danieldotnl/ha-multiscrape#107] opened 2022-04-10 08:49 UTC
Hi Daniel,

First of all many thanks for your great module multiscrape. After updating Home assistant and multiscrape, I got. an error-message. Home assistant does not view my entities I declared with multiscrape. After checking my logs, I located this behavour in the line where  I defined the unit of my measurement. I think that this depence by changes of the ‚core‘ Home Assistant 2022.4.1

thanks 

Erich

## Version of the custom_component

v5.7.0

## Configuration

If unit_of_measurement is used

## Describe the bug

When I use unit_of_measurement im my configuration.yaml i get the error. When comment out, everything works fine

## Debug log

Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:454 
Integration: Sensor (documentation, issues) 
First occurred: 10:33:24 (2 occurrences) 
Last logged: 10:33:24

Error adding entities for domain sensor with platform multiscrape
Error while setting up multiscrape platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 799, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 454, in state
    assert native_unit_of_measurement
AssertionError

```

**Comment by danieldotnl** [comment] 2022-04-10 09:02
Thanks for creating an issue. I didn't upgrade yet myself. I will look at it as soon as I can.

**Comment by Schnabulation** [comment] 2022-04-11 19:14
I can confirm that this is an issue that seems to be related with 2022.4.x. I noticed the same error with all sensors where the unit_of_measurement is declared.

After this is commented out, the sensor is working perfectly fine - but without the unit of course.

**Comment by Schnabulation** [comment] 2022-04-11 19:22
Another interesting thing: it seems to be the combination of

```
        unit_of_measurement: "°C"
        device_class: temperature
```

Because if you remove one of the two - doesn't matter which - the sensor works again.

**Comment by Schnabulation** [comment] 2022-04-11 19:58
I think I found the issue: Since the last update the user can configure the unit of temperature sensors in the frontend. This will in turn be stored in "unit_of_measurement". Because of that temperature sensor now need two new properties:

```
native_unit_of_measurement
native_value
```

You can read more here: https://developers.home-assistant.io/docs/core/entity/sensor/

I tried to declare this but it gives me a config error because multiscrape does not know these properties.

**Comment by wigster** [comment] 2022-04-11 21:00
There is also this when callling the multiscrape.trigger service. I think I have all my temperature device_classes commented out, but maybe I've missed something. The sensors themselves seem to be scraping ok.
```
Logger: homeassistant.components.script.multiscrape_update
Source: components/sensor/__init__.py:454
Integration: Scripts (documentation, issues)
First occurred: 22:56:32 (1 occurrences)
Last logged: 22:56:32

multiscrape_update: Error executing script. Unexpected error for call_service at pos 1:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 379, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 582, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/multiscrape/__init__.py", line 152, in _async_trigger_service
    await coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 144, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 78, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_refresh
    update_callback()
  File "/config/custom_components/multiscrape/entity.py", line 105, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 454, in state
    assert native_unit_of_measurement
AssertionError
```

**Comment by danieldotnl** [comment] 2022-04-12 19:18
Could you all please try out release pre-v6.1.0? Note that it does not only contain a fix for this issue, but also a significant refactoring of the code.

**Comment by ErichRa** [comment] 2022-04-13 04:37
I downloaded pre-v6.1.0 without changing my configuration.yaml (uncomment device_classes). Everything works fine. After this I changed to my original configuration with device_classes and unit_of_measurement, reset, -> no error message in log, no error or messages in my dashboards. Good job, many thanks Erich

**Comment by wigster** [comment] 2022-04-13 08:13
I've just tried  pre-6.1.0 here and indeed all is scraping fine.

**Comment by danieldotnl** [comment] 2022-04-13 18:06
> While this may fix existing configurations where `unit_of_measurement` and `device_class` is defined, personally I don't think that approach is accurate. Home Assistant introduced the values `native_unit_of_measurement` and `native_value` so I think it would be better to expose these values through multiscrape, no?

Would it be worth breaking the config of all users with no obvious advantage? The `template` sensor included in HA does the same thing...

**Comment by ErichRa** [comment] 2022-04-14 18:25
For me ist not clear why there is a special handling for devices with device_class temperature. 

>The unit of measurement that the sensor's value is expressed in. If the native_unit_of_measurement is °C or °F, and its device_class is temperature, the sensor's unit_of_measurement will be the preferred temperature unit configured by the user and the sensor's state will be the native_value after an optional unit conversion.

**Closed** 2022-04-19 08:14 UTC
