### ISSUE TITLE
Error after Core (2023.7.1) update

### ISSUE THREAD

**Issue by ostracizado** [danieldotnl/ha-multiscrape#216] opened 2023-07-07 00:14 UTC
Multiscrape: v6.7.0

```
Logger: homeassistant.setup
Source: core.py:1763
First occurred: 01:04:48 (1 occurrences)
Last logged: 01:04:48

Error during setup of component multiscrape
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/multiscrape/__init__.py", line 89, in async_setup
    return await _async_process_config(hass, entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/multiscrape/__init__.py", line 162, in _async_process_config
    await _register_services(hass, target_name, coordinator)
  File "/config/custom_components/multiscrape/__init__.py", line 208, in _register_services
    async_set_service_schema(hass, DOMAIN, target_name, service_desc)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 687, in async_set_service_schema
    response := hass.services.supports_response(domain, service)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1763, in supports_response
    if not (handler := self._services[domain][service]):
                       ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'net_radiation'
```
```
multiscrape:
  - name: Net Radiation
    resource: https://en.tutiempo.net/solar-radiation/###-district/###.html
    scan_interval: 3600
    sensor:
      - unique_id: net_radiation_8am
        name: 8am
        select: "div#HorasDia1 div:nth-child(1) > span.ener > strong"
        unit_of_measurement: "Wh/m²"
      - unique_id: net_radiation_9am
        name: 9am
        select: "div#HorasDia1 div:nth-child(2) > span.ener > strong"
        unit_of_measurement: "Wh/m²"
      - unique_id: net_radiation_10am
        name: 10am
        select: "div#HorasDia1 div:nth-child(3) > span.ener > strong"
        unit_of_measurement: "Wh/m²"
      - unique_id: net_radiation_11am
        name: 11am
        select: "div#HorasDia1 div:nth-child(4) > span.ener > strong"
        unit_of_measurement: "Wh/m²"
      - unique_id: net_radiation_12am
        name: 12am
        select: "div#HorasDia1 div:nth-child(5) > span.ener > strong"
        unit_of_measurement: "Wh/m²"
      - unique_id: net_radiation_1pm
        name: 1pm
        select: "div#HorasDia1 div:nth-child(6) > span.ener > strong"
        unit_of_measurement: "Wh/m²"
      - unique_id: net_radiation_2pm
        name: 2pm
        select: "div#HorasDia1 div:nth-child(7) > span.ener > strong"
        unit_of_measurement: "Wh/m²"
      - unique_id: net_radiation_3pm
        name: 3pm
        select: "div#HorasDia1 div:nth-child(8) > span.ener > strong"
        unit_of_measurement: "Wh/m²"
      - unique_id: net_radiation_4pm
        name: 4pm
        select: "div#HorasDia1 div:nth-child(9) > span.ener > strong"
        unit_of_measurement: "Wh/m²"
      - unique_id: net_radiation_5pm
        name: 5pm
        select: "div#HorasDia1 div:nth-child(10) > span.ener > strong"
        unit_of_measurement: "Wh/m²"
```

**Comment by codyc1515** [comment] 2023-07-07 00:34
Duplicate of #215

**Closed** 2023-07-07 07:49 UTC

**Comment by codyc1515** [comment] 2023-07-07 09:24
Fixed by https://github.com/danieldotnl/ha-multiscrape/commit/683d63f0f1176ea75a99f5bcb407f62999c45295
